# Jekyll configuration

name: "Desert stories"
description: '<img src="/images/logo.png"><p>Read the latest news on your favorite group of desert travelers: the <a href="/lineup.html">Wasteland Heroes</a>!</p>'

# url is currently only used only for the RSS feed in feed.xml
url: http://wastelandheroes.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'none'
comments: false

gems: [jekyll-paginate]

permalink: /:year/:month/:title
paginate: 5

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    parse_block_html: true
    parse_span_html: true
    smart_quotes: lsquo,rsquo,ldquo,rdquo
highlighter: pygments

exclude: ['README.md', 'LICENSE']
